### ISSUE TITLE
Question: What is the default user?

### ISSUE THREAD

**Issue by michelob** [agentejo/cockpit-docker#1]
Hi,

Thank you for the docker file...what is the default user to log in with once I have the image up and running?

If there is no default user, what is the path to register?

Thanks
-michelob

**Comment by aheinze** [comment]
Open the URL /install that's it

**Comment by michelob** [comment]
Nice!

**Comment by gustawdaniel** [comment]
Definitely, it should be automatically detected. The current solution is counterintuitive.

**Comment by tsener** [comment]
the /install routine should be documented on the Dockerhub page.
