### ISSUE TITLE
Login???

### ISSUE THREAD

**Issue by bzerangue** [agentejo/cockpit-docker#3]
Followed your instructions for install, what is the login? (username and password)

**Comment by chris-aeviator** [comment]
@bzerangue what was the login & password, facing the same issue :)

**Comment by Bathlamos** [comment]
@chris-aeviator visiting `/admin` helps solve this issue

**Comment by rm-rf-etc** [comment]
Why was this issue closed? Visiting `/admin` redirects to the same page. I can't login. What is the point if nobody can login?

**Comment by rm-rf-etc** [comment]
Found the answer here: https://github.com/agentejo/cockpit/issues/619

**Comment by chris-aeviator** [comment]
Visit `/install`

Am 1. Juli 2019 05:42:46 MESZ schrieb Rob <notifications@github.com>:
