### ISSUE TITLE
Don't add config directory as volume

### ISSUE THREAD

**Issue by eXaminator** [agentejo/cockpit-docker#8]
Hey everyone.

So, by default the config directory is configured to be a volume. I'd much rather bake the configuration into my own image which I derived from this one. But I can't add files to the config directory, because docker doesn't save changes made to a directory in an image after that directory was marked as a volume. Hence I can't put my own configuration or even the translations into my image, I would HAVE to put those on my host and mount that volume.

I know that I can actually change the config directory path using defines.php, and I tried that. But this breaks for TinyMCE translations because the path for those is hardcoded.

So instead of doing that I'd prefer to be able to change the contents of my config directory in my own image.

If the VOLUMES configuration was removed from the Dockerfile it would still be possible to mount that directory if people want that.

**Comment by sambernet** [comment]
Fully agree with all your opinions, same situation here.

I also implemented the workaround of using a custom `defines.php` to move the config volume, then mounting a `tmpfs` volume to the original location defined in the `Dockerfile`. This at least eliminates the volume that is not used anyway and avoids some confusion.

I wasn't aware of this breaking anything as I didn't configure any languages...
